# Note: Only postgres 8.4+ is supported!

common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *common
  database: layer_development

test:
  <<: *common
  database: layer_test

production:
  <<: *common
  database: layer_production
